# Generated by Django 5.0 on 2023-12-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('link', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=500)),
                ('tag', models.CharField(default='others', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notes',
            },
        ),
    ]
